BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Commande_Kit";
CREATE TABLE IF NOT EXISTS "Commande_Kit" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_kit"	INTEGER NOT NULL,
	"h_envoi"	TEXT,
	"h_recep"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Commande_piece";
CREATE TABLE IF NOT EXISTS "Commande_piece" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_piece"	INTEGER NOT NULL,
	"h_envoi"	TEXT,
	"h_recep"	TEXT,
	"quantite"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Erreur";
CREATE TABLE IF NOT EXISTS "Erreur" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_commande"	INTEGER NOT NULL,
	"id_piece"	INTEGER NOT NULL,
	"quantite"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Kits";
CREATE TABLE IF NOT EXISTS "Kits" (
	"id"	INTEGER NOT NULL UNIQUE,
	"nom_kit"	TEXT UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Pieces";
CREATE TABLE IF NOT EXISTS "Pieces" (
	"id"	INTEGER NOT NULL UNIQUE,
	"ref"	TEXT NOT NULL,
	"nom_piece"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Stock_Agilog";
CREATE TABLE IF NOT EXISTS "Stock_Agilog" (
	"id"	INTEGER NOT NULL UNIQUE,
	"quantite"	INTEGER NOT NULL,
	"seuil_commande"	INTEGER,
	"id_piece"	INTEGER,
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "Composition_Kit";
CREATE TABLE IF NOT EXISTS "Composition_Kit" (
	"id_Kit"	INTEGER NOT NULL,
	"id_piece"	INTEGER NOT NULL,
	"quantitee"	INTEGER
);
COMMIT;
